# ------------------------------
# system config
# ------------------------------

appName: myApp # name of your app without spaces

timezoneOnCreate: UTC # recommended to use UTC when storing time then just adjust time upon read
timezoneOnRead: UTC # change to your local timezone

dateTimeMysqlFormat: Y-m-d H:i:s
dateTimeHumanFormat: r

viewsPath: Views/Default/
viewsPathLowercase: views/default/

languagesPath: src/App/Languages/
language: en-US

credsPath: config/creds/creds.yaml.enc # used in dev mode or in shared server (e.g., Cpanel)

# ------------------------------
# db tables
# ------------------------------

errorLogTable: errorLog
optionsTable: options

mrfwTempBanTable: mrfwTempBan
mrfwExtendedBanTable: mrfwExtendedBan
mrfwWhitelistTable: mrfwWhitelist
mrfwFailCountTable: mrfwFailCount
mrfwBlockCountTable: mrfwBlockCount

# ------------------------------
# app config
# ------------------------------
